version: '3'

services:
    sdc:
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        container_name: dapp
        ports:
            - 8082:80
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/code
        working_dir: /code
        depends_on:
        #  - mongodb
            - mysql

    mysql:
       container_name: mysql_dapp
       image: mysql:8.0
    #     ports:
    #       - 3306:3306
       environment:
            MYSQL_ROOT_PASSWORD: mysqlroot
            MYSQL_DATABASE: sdc_dapp
    #         MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    #     logging:
    #         driver: none

    phpmyadmin:
        container_name: pma_dapp
        image: phpmyadmin
        ports:
            - 8083:80
        environment:
            - PMA_ARBITRARY=1
